name: NABS Workflow (PyYPSH Runtime)

on:
  release:
    types: [published]

jobs:
  release-python-file:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Update pip and Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install rich ulid-py

      - name: Configurate PyYPSH Python Script for Python Script Source Version
        shell: bash
        run: |
          python configurator.py -i ypsh.py -o YPSH-python-3.py -t ${{ github.event.release.tag_name || github.ref }} -s

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: YPSH-python-3.py
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  release-binary-files:
    continue-on-error: true
    strategy:
      matrix:
        include:
          - os: macos-13
            platform: macOS Intel
            filename: YPSH-macos-AMD64
          - os: ubuntu-22.04
            platform: Linux Intel/AMD
            filename: YPSH-linux-AMD64
          - os: windows-2022
            platform: Windows Intel/AMD
            filename: YPSH-windows-AMD64
          - os: macos-14
            platform: macOS Apple Silicon
            filename: YPSH-macos-arm64
          - os: ubuntu-22.04-arm
            platform: Linux ARM
            filename: YPSH-linux-arm64
          - os: windows-11-arm
            platform: Windows ARM
            filename: YPSH-windows-arm64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Update pip and Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install rich ulid-py zstandard

      - name: Configurate PyYPSH Python Script for Release Version
        shell: bash
        run: |
          python configurator.py -i ypsh.py -o main.py -t ${{ github.event.release.tag_name || github.ref }}

      - name: Build (non-windows)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          python build.py -f main.py -m pyinstaller -o upload/${{ matrix.filename }}
          python build.py -f main.py -m nuitka -o upload/${{ matrix.filename }}-NUI

      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          python build.py -f main.py -m pyinstaller -o upload/${{ matrix.filename }}.exe
          python build.py -f main.py -m nuitka -o upload/${{ matrix.filename }}-NUI.exe

      - name: Zip (non-windows)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          cd upload
          zip "${{ matrix.filename }}.zip" "${{ matrix.filename }}"
          zip "${{ matrix.filename }}-NUI.zip" "${{ matrix.filename }}-NUI"

      - name: Zip (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Compress-Archive -Path "upload/${{ matrix.filename }}.exe" -DestinationPath "upload/${{ matrix.filename }}.zip"
          Compress-Archive -Path "upload/${{ matrix.filename }}-NUI.exe" -DestinationPath "upload/${{ matrix.filename }}-NUI.zip"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: upload/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  update-release-channels:
    needs: [release-python-file, release-binary-files]
    runs-on: ubuntu-22.04
    if: ${{ success() && github.event_name == 'release' }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}

      - name: Set up Git
        run: |
          git config user.name "NABS Workflow"
          git config user.email "github@bots.diamondgotcat.net"

      - name: Update release channels
        shell: bash
        run: |
          tag="${{ github.event.release.tag_name }}"
          mkdir -p channels
          echo "$tag" > channels/beta.txt

          if [[ "${{ github.event.release.prerelease }}" == "false" ]]; then
            echo "$tag" > channels/maybe-stable.txt
          fi

          git add channels/beta.txt
          if [[ "${{ github.event.release.prerelease }}" == "false" ]]; then
            git add channels/maybe-stable.txt
          fi

          git commit -m "Update release channels to $tag" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git push origin HEAD:main
